### ISSUE TITLE
运行pair_train.py文件失败

### ISSUE THREAD

**Issue by huanhuancao** [ahangchen/TFusion#11]
运行完train.py文件之后得到.h5文件，运行pair_train.py文件时，出现以下错误，试了很多种方法，无果！求大佬们帮忙看一下！
**`Traceback (most recent call last):
  File "/home/chh/Code/TFusion-master/rank-reid/pretrain/pair_train.py", line 236, in <module>
    pair_pretrain_on_dataset(source)
  File "/home/chh/Code/TFusion-master/rank-reid/pretrain/pair_train.py", line 224, in pair_pretrain_on_dataset
    batch_size=batch_size, num_classes=class_count
  File "/home/chh/Code/TFusion-master/rank-reid/pretrain/pair_train.py", line 153, in pair_tune
    model = pair_model(source_model_path, num_classes)
  File "/home/chh/Code/TFusion-master/rank-reid/pretrain/pair_train.py", line 124, in pair_model
    feature1 = Flatten()(base_model(img1))
  File "/home/chh/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/chh/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 2085, in call
    output_tensors, _, _ = self.run_internal_graph(inputs, masks)
  File "/home/chh/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 2236, in run_internal_graph
    output_tensors = _to_list(layer.call(computed_tensor, **kwargs))
  File "/home/chh/anaconda3/lib/python3.6/site-packages/keras/layers/normalization.py", line 193, in call
    self.momentum),
  File "/home/chh/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 1005, in moving_average_update
    x, value, momentum, zero_debias=True)
  File "/home/chh/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/moving_averages.py", line 71, in assign_moving_average
    update_delta = _zero_debias(variable, value, decay)
  File "/home/chh/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/moving_averages.py", line 181, in _zero_debias
    biased_var = variable_scope.get_variable("biased", initializer=biased_initializer, trainable=False)
  File "/home/chh/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 988, in get_variable
    custom_getter=custom_getter)
  File "/home/chh/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 890, in get_variable
    custom_getter=custom_getter)
  File "/home/chh/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 348, in get_variable
    validate_shape=validate_shape)
  File "/home/chh/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 333, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/home/chh/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 639, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable bn_conv1/moving_mean/biased already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "/home/chh/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 1005, in moving_average_update
    x, value, momentum, zero_debias=True)
  File "/home/chh/anaconda3/lib/python3.6/site-packages/keras/layers/normalization.py", line 193, in call
    self.momentum),
  File "/home/chh/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)`**

**Comment by ahangchen** [comment]
Please follow the instruction and use python2.7 & Keras2.1.5 & tensorflow 1.4. 

It seems that the Flatten is applied to a BN layer, which is strange.  Maybe you can add a breakpoint to see what type is `base_model(img1)`
