### ISSUE TITLE
.log 相关问题

### ISSUE THREAD

**Issue by Eileen2014** [ahangchen/TFusion#17]
作者你好，我在运行 transfer.py 的时候出现了如下错误：
Traceback (most recent call last):
  File "transfer.py", line 131, in <module>
    dataset_fusion_transfer()
  File "transfer.py", line 124, in dataset_fusion_transfer
    fusion_transfer(source, 'grid-cv%d' % i)
  File "transfer.py", line 96, in fusion_transfer
    fusion_test_rank_pids_path, fusion_test_rank_scores_path = st_fusion(source, target)
  File "transfer.py", line 45, in st_fusion
    init_strict_img_st_fusion()
  File "/home/cv2018/Desktop/TFusion-master/TrackViz/ctrl/img_st_fusion.py", line 48, in init_strict_img_st_fusion
    get_predict_delta_tracks(fusion_param)
  File "/home/cv2018/Desktop/TFusion-master/TrackViz/train/st_estim.py", line 57, in get_predict_delta_tracks
    predict_lines = read_lines(renew_pid_path)
  File "/home/cv2018/Desktop/TFusion-master/TrackViz/util/file_helper.py", line 15, in read_lines
    with open(path) as f:
IOError: [Errno 2] No such file or directory: '/home/cv2018/Desktop/TFusion-master/TrackViz/data/market_market-test/renew_pid.log'
请问 renew_pid.log 是要自己手动导入吗？求解答！

**Comment by ahangchen** [comment]
参考这里 #6
